---
- name: Install & update httpd
  yum:
    name: httpd
    state: latest
  when: ansible_os_family == "RedHat"

- name: Allow the http port
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Delete Indexes from Options of /var/www/html
  lineinfile:
    dest: /etc/httpd/conf/httpd.conf
    regexp: "(\\s*)Options(.*)Indexes(.*)"
    line: "\\1Options \\2 \\3"
    state: present
    backup: yes
    backrefs: yes

- name: Deploy the security.conf
  copy:
    src: security.conf
    dest: /etc/httpd/conf.d
    mode: 0644

- name: Restart httpd
  systemd:
    name: httpd
    state: restarted
    daemon_reload: yes
    enabled: yes