---
- name: Install & update httpd
  yum:
    name: httpd
    state: latest
  when: ansible_os_family == "RedHat"

- name: Allow the http port
  firewalld:
    port: 80/tcp
    permanent: yes
    immediate: yes
    state: enabled

- name: Restart httpd
  systemd:
    name: httpd
    state: restarted
    daemon_reload: yes
    enabled: yes